apiVersion: v1
kind: Service
metadata:
  name: fittrack
  namespace: fittrack
  labels:
    app: fittrack
spec:
  selector:
    app: fittrack
  ports:
    - port: 80
      targetPort: http
      name: http
  type: ClusterIP
